app/servicio_social/instituciones/urls.py
from django.urls import path
from . import views

# /unidades/lista
urlpatterns = [
    path('lista/', views.ListaInstituciones.as_view(), name='lista_instituciones'),
    path('nueva/', views.NuevaInstitucion.as_view(), name='nueva_institucion'),
    # path('nueva-ajax/', views.nueva_unidad_ajax, name='nueva_unidad_ajax'),
    path('eliminar/<int:pk>', views.EliminarInstitucion.as_view(), name='eliminar_institucion'),
    path('editar/<int:pk>', views.EditarInstitucion.as_view(), name='editar_institucion'),
]

app/servicio_social/programa_academico/urls.py
from django.urls import path
from . import views

# /unidades/lista
urlpatterns = [
    path('lista/', views.lista_unidades_academicas, name='lista_unidades'),
    path('nueva/', views.nueva_unidad, name='nueva_unidad'),
    path('nueva-ajax/', views.nueva_unidad_ajax, name='nueva_unidad_ajax'),
    path('eliminar/<int:id>', views.eliminar_unidad, name='eliminar_unidad'),
    path('editar/<int:id>', views.editar_unidad, name='editar_unidad'),
]

app/servicio_social/servicio_social/urls.py
from django.contrib import admin
from django.urls import path, include
from programa_academico.views import bienvenida
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from api.views import ProgramaAcademicoViewSet

router = routers.DefaultRouter()
router.register(r'programas-api', ProgramaAcademicoViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('unidades/', include('programa_academico.urls')),
    path('instituciones/', include('instituciones.urls')),
    path('programas/', include('programa_academico.urls_programas')),
    path('', bienvenida, name='bienvenida'),
    path('', include(router.urls)),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/servicio_social/programa_academico/models.py
from django.db import models

# CRUD

# READ 
class UnidadAcademica(models.Model):
    nombre = models.CharField(max_length=150)
    descripcion = models.TextField('Descripción')

    def __str__(self):
        return self.nombre

class ProgramaAcademico(models.Model):
    nombre = models.CharField(max_length=150)
    descripcion = models.TextField('Descripción')
    unidad_academica = models.ForeignKey("programa_academico.UnidadAcademica",
            verbose_name='Unidad Académica', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nombre

app/servicio_social/programa_academico/forms.py
from django import forms
from .models import UnidadAcademica, ProgramaAcademico

class FormUnidadAcademica(forms.ModelForm):
    
    class Meta:
        model = UnidadAcademica
        fields = '__all__'
        # fields = ['nombre']
        # exclude = ['nombre']
        
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'UAIE'
                }
            ),
            'descripcion': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Escribe una descripción...'
                }
            )
        }
        
        
class FormProgramaAcademico(forms.ModelForm):
    
    class Meta:
        model = ProgramaAcademico
        fields = '__all__'
        # fields = ['nombre']
        # exclude = ['nombre']
        
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'UAIE'
                }
            ),
            'unidad_academica': forms.Select(
                attrs={
                    'class':'form-control',
                }
            ),
            'descripcion': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Escribe una descripción...'
                }
            )
        }
        
class FormFiltrosPrograma(forms.Form):
    nombre = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'placeholder':'Nombre','class':'form-control'}))
    descripcion = forms.CharField(required=False,
        widget=forms.TextInput(attrs={'placeholder':'Descripción','class':'form-control'}))
    unidad = forms.CharField(required=False,
        widget=forms.TextInput(attrs={'placeholder':'Unidad','class':'form-control'}))

app/servicio_social/programa_academico/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import UnidadAcademica, ProgramaAcademico
from .forms import FormUnidadAcademica, FormProgramaAcademico, FormFiltrosPrograma

def bienvenida(request):
    return render(request, 'bienvenida.html')
    

def editar_unidad(request, id):
    unidad = UnidadAcademica.objects.get(id=id)
    if request.method == 'POST':
        form = FormUnidadAcademica(request.POST, instance=unidad)
        if form.is_valid():
            form.save()
            return redirect('lista_unidades')
    else: 
        form = FormUnidadAcademica(instance=unidad)
    context = {'form': form }
    return render(request, 'editar_unidad.html', context)

def nuevo_programa(request): 
    form_unidad = FormUnidadAcademica()
    if request.method == 'POST':
        form = FormProgramaAcademico(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_unidades')

    else:
        form = FormProgramaAcademico()
    
    context = {'form': form, 'form_unidad': form_unidad }
    return render(request, 'nuevo_programa.html', context)

def nueva_unidad_ajax(request):
    if request.method == 'POST':
        form = FormUnidadAcademica(request.POST)
        if form.is_valid():
            unidad = form.save()
            unidades = list(UnidadAcademica.objects.all().values())
            response = {
                'ok':'Se guardó la unidad con éxito',
                'unidades': unidades,
                'unidad': unidad.id
            }
            return JsonResponse(response, safe=False)
        else:
            return JsonResponse({'error': f"Error de validación: {form.errors}"}, safe=False)
    else:
        return JsonResponse({'error':'Método no permitido'}, safe=False)

   
def nueva_unidad(request):
    if request.method == 'POST':
        form = FormUnidadAcademica(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_unidades')

    else:
        form = FormUnidadAcademica()
    
    context = {'form': form }
    return render(request, 'nueva_unidad.html', context)
    

def lista_unidades_academicas(request):
    context = {'unidades': UnidadAcademica.objects.all()}
    return render(request, 'lista_unidades.html', context)


def lista_programas(request):
    programas = ProgramaAcademico.objects.all()
    # programas = ProgramaAcademico.objects.get(id=2)
    # programas = ProgramaAcademico.objects.filter(nombre='Ingeniería de Software')
    # programas = ProgramaAcademico.objects.filter(nombre__startswith='I')
    # programas = ProgramaAcademico.objects.filter(nombre__endswith='ware')
    # programas = ProgramaAcademico.objects.filter(nombre__icontains='soft')
    # programas = ProgramaAcademico.objects.filter(nombre__iexact='soft')

    # programas = ProgramaAcademico.objects.exclude(nombre__startswith='I')[:2]
    # programas = ProgramaAcademico.objects.exclude(nombre__startswith='I')[2:4]
    
    print(programas.query)
    
    paginator = Paginator(programas, 2)
    page_number = request.GET.get("page")
    programas = paginator.get_page(page_number)

    if request.method == 'POST':
        form = FormFiltrosPrograma(request.POST)
        
        nombre = request.POST.get('nombre', None)
        descripcion = request.POST.get('descripcion', None)
        unidad = request.POST.get('unidad', None)
        
        if nombre:
            programas = programas.filter(nombre=nombre)
        
        if descripcion:
            programas = programas.filter(descripcion__icontains=descripcion)
                
        if unidad:
            programas = programas.filter(unidad_academica__nombre=unidad)

    else:
        form = FormFiltrosPrograma()
    context = {'programas': programas, 'form':form}
    return render(request, 'lista_programas.html', context)

def eliminar_unidad(request, id):
    unidad = UnidadAcademica.objects.get(id=id)
    programas = ProgramaAcademico.objects.filter(unidad_academica=unidad)
    print(programas)
    for programa in programas:
        programa.delete()
        
    unidad.delete()
    return redirect('lista_unidades')

app/servicio_social/programa_academico/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <title>
        {% block titulo %}

        {% endblock titulo %}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'bienvenida' %}">UAIE | SS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'bienvenida' %}">Incio</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Unidades
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'nueva_unidad' %}">Nueva</a></li>
                            <li><a class="dropdown-item" href="{% url 'lista_unidades' %}">Lista</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Programas
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'nuevo_programa' %}">Nuevo</a></li>
                            <li><a class="dropdown-item" href="{% url 'lista_programas' %}">Lista</a></li>
                        </ul>
                    </li>

                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        <br>
        {% block contenido %}

        {% endblock contenido %}
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    {% block scripts %}

    {% endblock scripts %}

</body>

</html>

app/servicio_social/programa_academico/templates/bienvenida.html
{% extends 'base2.html' %}


{% block titulo %}
Bienvenida al Sistema de SS
{% endblock titulo %}


{% block contenido %}
<br>
<hr>
<h1>Bienvenid@ al Sistema de Servicio Social</h1>
{% endblock contenido %}

app/servicio_social/programa_academico/templates/editar_unidad.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar unidad</title>
</head>

<body>
    <h1>Actualizar unidad</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Guardar</button>
        <a href="{% url 'lista_unidades' %}">Cancelar</a>

    </form>
</body>

</html>

app/servicio_social/programa_academico/templates/lista_programas.html
{% extends 'base2.html' %}

{% block titulo %}
Programas académicos
{% endblock titulo %}

{% block contenido %}
<h1>Programas académicos UAZ</h1>
<a class="btn btn-primary" href="{% url 'nuevo_programa' %}">Nuevo programa</a>

<form method="post">
    {% csrf_token %}
    <table class="table">
        <thead>
            <tr>
                <td></td>
                <td>{{form.nombre}}</td>
                <td>{{form.descripcion}}</td>
                <td>{{form.unidad}}</td>
                <td>
                    <button class="btn btn-primary bt-sm" type="submit">Buscar</button>
                </td>
            </tr>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Unidad</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for programa in programas %}
            <tr>
                <td>{{programa.id}}</td>
                <td>{{programa.nombre}}</td>
                <td>{{programa.descripcion}}</td>
                <td>{{programa.unidad_academica.nombre}}</td>
                <td>
                    <a class="btn btn-outline-danger btn-sm" href="#">Eliminar</a>
                    <a class="btn btn-outline-primary btn-sm" href="#">Editar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
<div class="pagination">
    <span class="step-links">
        {% if programas.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ programas.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ programas.number }} of {{ programas.paginator.num_pages }}.
        </span>

        {% if programas.has_next %}
        <a href="?page={{ programas.next_page_number }}">next</a>
        <a href="?page={{ programas.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<div>
    <select name="cuantos">
        <option value="5">5</option>
        <option value="10">10</option>
        <option value="15">15</option>
        <option value="20">20</option>
        <option value="25">25</option>
    </select>
</div>
{% endblock contenido %}

app/servicio_social/programa_academico/templates/lista_unidades.html
{% extends 'base2.html' %}

{% block titulo %}
Unidades académicas
{% endblock titulo %}

{% block contenido %}
<h1>Unidades académicas UAZ</h1>
<a class="btn btn-primary" href="{% url 'nueva_unidad' %}">Nueva unidad</a>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for unidad in unidades %}
        <tr>
            <td>{{unidad.id}}</td>
            <td>{{unidad.nombre}}</td>
            <td>{{unidad.descripcion}}</td>
            <td>
                <a class="btn btn-outline-danger btn-sm" href="{% url 'eliminar_unidad' unidad.id %}">Eliminar</a>
                <a class="btn btn-outline-primary btn-sm" href="{% url 'editar_unidad' unidad.id %}">Editar</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock contenido %}

app/servicio_social/programa_academico/templates/nueva_unidad.html
{% extends 'base2.html' %}

{% block titulo %}
Nueva unidad
{% endblock titulo %}

{% block contenido %}
<h1>Nueva unidad</h1>
<form method="post" class="form">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success" type="submit">Agregar</button>
    <a class="btn btn-warning" href="{% url 'lista_unidades' %}">Cancelar</a>
</form>

{% endblock contenido %}

app/servicio_social/programa_academico/templates/nuevo_programa.html
{% extends 'base2.html' %}

{% block titulo %}
Nuevo programa
{% endblock titulo %}

{% block contenido %}
<h1>Nuevo programa</h1>
<form method="post" class="form">
    {% csrf_token %}
    <div class="row mb-3">
        <div class="col-8">
            {{ form.nombre.label_tag }}
            {{ form.nombre }}

        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            {{ form.descripcion.label_tag }}
            {{ form.descripcion }}
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-10">
            {{ form.unidad_academica.label_tag }}
            {{ form.unidad_academica }}
        </div>
        <div class="col-2 align-middle">
            <button type="button" class="btn mt-2" data-bs-toggle="modal" data-bs-target="#unidadModal">
                <i class="bi bi-plus-circle-fill fs-3"></i>
            </button>
        </div>
    </div>
    <button class="btn btn-success " type="submit">Agregar</button>
    <a class="btn btn-warning" href="{% url 'lista_programas' %}">Cancelar</a>
</form>


<div class="modal fade" id="unidadModal" tabindex="-1" aria-labelledby="unidadModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="unidadModalLabel">Nueva unidad</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'nueva_unidad_ajax' %}" class="form" id="formUnidad">
                <div class="modal-body">
                    {% csrf_token %}
                    {{form_unidad.as_p}}
                </div>
                <div class="modal-footer">
                    <button id="btnCerrar" type="button" class="btn btn-secondary"
                        data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}


{% block scripts %}
<script>
    $("#formUnidad").submit(function (e) {
        e.preventDefault();
        var form = $(this);
        var url = form.attr("action");
        console.log(form.serialize());
        $.ajax({
            type: "POST",
            url: url,
            data: form.serialize(),
            success: function (data) {
                console.log(data);
                if (data.ok) {
                    var html = ""
                    $.each(data.unidades, function (llave, valor) {
                        var seleccion = (valor.id == data.unidad) ? "selected" : "";
                        html += `<option ${seleccion} value="${valor.id}">${valor.nombre}</option>`;
                    });
                    $("#id_unidad_academica").html(html);
                    $("#btnCerrar").click();
                }
                else {
                    var error = `<div class="alert alert-danger">${data.error}</div>`;
                    $(".modal-body").prepend(error);
                }

            }
        });
    });
</script>
{% endblock scripts %}